// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"vine-template-rpc/internal/conf"
	"vine-template-rpc/internal/server"
	"vine-template-rpc/internal/system/biz"
	"vine-template-rpc/internal/system/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	userBiz := biz.NewUserBiz()
	systemService := service.NewSystemService(userBiz)
	grpcServer := server.NewGRPCServer(confServer, systemService, logger)
	httpServer := server.NewHTTPServer(confServer, systemService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
