// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TbAlarmRuleColumns holds the columns for the "tb_alarm_rule" table.
	TbAlarmRuleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "level", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "remark", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeInt, Default: 1},
		{Name: "create_time", Type: field.TypeString, Nullable: true},
		{Name: "creator", Type: field.TypeString, Nullable: true},
	}
	// TbAlarmRuleTable holds the schema information for the "tb_alarm_rule" table.
	TbAlarmRuleTable = &schema.Table{
		Name:       "tb_alarm_rule",
		Columns:    TbAlarmRuleColumns,
		PrimaryKey: []*schema.Column{TbAlarmRuleColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TbAlarmRuleTable,
	}
)

func init() {
	TbAlarmRuleTable.Annotation = &entsql.Annotation{
		Table: "tb_alarm_rule",
	}
}
