// Code generated by ent, DO NOT EDIT.

package ent

import (
	"vine-template-rpc/internal/emonitor/data/ent/equipment"
	"vine-template-rpc/internal/emonitor/data/ent/schema"
	"vine-template-rpc/internal/emonitor/data/ent/site"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	equipmentFields := schema.Equipment{}.Fields()
	_ = equipmentFields
	// equipmentDescID is the schema descriptor for id field.
	equipmentDescID := equipmentFields[0].Descriptor()
	// equipment.DefaultID holds the default value on creation for the id field.
	equipment.DefaultID = equipmentDescID.Default.(func() uuid.UUID)
	siteFields := schema.Site{}.Fields()
	_ = siteFields
	// siteDescStatus is the schema descriptor for status field.
	siteDescStatus := siteFields[8].Descriptor()
	// site.DefaultStatus holds the default value on creation for the status field.
	site.DefaultStatus = siteDescStatus.Default.(int)
	// siteDescID is the schema descriptor for id field.
	siteDescID := siteFields[0].Descriptor()
	// site.DefaultID holds the default value on creation for the id field.
	site.DefaultID = siteDescID.Default.(func() uuid.UUID)
}
