// Code generated by ent, DO NOT EDIT.

package ent

import (
	"vine-template-rpc/internal/alarm/data/ent/rule"
	"vine-template-rpc/internal/alarm/data/ent/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	ruleFields := schema.Rule{}.Fields()
	_ = ruleFields
	// ruleDescStatus is the schema descriptor for status field.
	ruleDescStatus := ruleFields[6].Descriptor()
	// rule.DefaultStatus holds the default value on creation for the status field.
	rule.DefaultStatus = ruleDescStatus.Default.(int)
	// ruleDescID is the schema descriptor for id field.
	ruleDescID := ruleFields[0].Descriptor()
	// rule.DefaultID holds the default value on creation for the id field.
	rule.DefaultID = ruleDescID.Default.(func() uuid.UUID)
}
