// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TbResourceColumns holds the columns for the "tb_resource" table.
	TbResourceColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "code", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "remark", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt, Default: 1},
	}
	// TbResourceTable holds the schema information for the "tb_resource" table.
	TbResourceTable = &schema.Table{
		Name:       "tb_resource",
		Columns:    TbResourceColumns,
		PrimaryKey: []*schema.Column{TbResourceColumns[0]},
	}
	// TbRoleColumns holds the columns for the "tb_role" table.
	TbRoleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeInt, Default: 1},
	}
	// TbRoleTable holds the schema information for the "tb_role" table.
	TbRoleTable = &schema.Table{
		Name:       "tb_role",
		Columns:    TbRoleColumns,
		PrimaryKey: []*schema.Column{TbRoleColumns[0]},
	}
	// TbUserColumns holds the columns for the "tb_user" table.
	TbUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "password", Type: field.TypeString},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
		{Name: "introduction", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "address", Type: field.TypeString, Nullable: true},
		{Name: "remark", Type: field.TypeString, Nullable: true},
		{Name: "type", Type: field.TypeString, Default: "1"},
		{Name: "status", Type: field.TypeInt, Default: 1},
	}
	// TbUserTable holds the schema information for the "tb_user" table.
	TbUserTable = &schema.Table{
		Name:       "tb_user",
		Columns:    TbUserColumns,
		PrimaryKey: []*schema.Column{TbUserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TbResourceTable,
		TbRoleTable,
		TbUserTable,
	}
)

func init() {
	TbResourceTable.Annotation = &entsql.Annotation{
		Table: "tb_resource",
	}
	TbRoleTable.Annotation = &entsql.Annotation{
		Table: "tb_role",
	}
	TbUserTable.Annotation = &entsql.Annotation{
		Table: "tb_user",
	}
}
