// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v4.25.1
// source: order/v1/order.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOrderAddOrder = "/api.order.v1.Order/AddOrder"
const OperationOrderReviewOrder = "/api.order.v1.Order/ReviewOrder"

type OrderHTTPServer interface {
	AddOrder(context.Context, *AddOrderRequest) (*AddOrderReply, error)
	// ReviewOrder 审核工单
	ReviewOrder(context.Context, *ReviewOrderRequest) (*ReviewOrderReply, error)
}

func RegisterOrderHTTPServer(s *http.Server, srv OrderHTTPServer) {
	r := s.Route("/")
	r.POST("/order/add", _Order_AddOrder0_HTTP_Handler(srv))
	r.POST("/order/review", _Order_ReviewOrder0_HTTP_Handler(srv))
}

func _Order_AddOrder0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderAddOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddOrder(ctx, req.(*AddOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddOrderReply)
		return ctx.Result(200, reply)
	}
}

func _Order_ReviewOrder0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReviewOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderReviewOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReviewOrder(ctx, req.(*ReviewOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReviewOrderReply)
		return ctx.Result(200, reply)
	}
}

type OrderHTTPClient interface {
	AddOrder(ctx context.Context, req *AddOrderRequest, opts ...http.CallOption) (rsp *AddOrderReply, err error)
	ReviewOrder(ctx context.Context, req *ReviewOrderRequest, opts ...http.CallOption) (rsp *ReviewOrderReply, err error)
}

type OrderHTTPClientImpl struct {
	cc *http.Client
}

func NewOrderHTTPClient(client *http.Client) OrderHTTPClient {
	return &OrderHTTPClientImpl{client}
}

func (c *OrderHTTPClientImpl) AddOrder(ctx context.Context, in *AddOrderRequest, opts ...http.CallOption) (*AddOrderReply, error) {
	var out AddOrderReply
	pattern := "/order/add"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderAddOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) ReviewOrder(ctx context.Context, in *ReviewOrderRequest, opts ...http.CallOption) (*ReviewOrderReply, error) {
	var out ReviewOrderReply
	pattern := "/order/review"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderReviewOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
