// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Car is the predicate function for car builders.
type Car func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Equipment is the predicate function for equipment builders.
type Equipment func(*sql.Selector)

// Site is the predicate function for site builders.
type Site func(*sql.Selector)
