// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"vine-template-rpc/internal/authz"
	"vine-template-rpc/internal/conf"
	"vine-template-rpc/internal/server"
	"vine-template-rpc/internal/system/biz"
	"vine-template-rpc/internal/system/data"
	"vine-template-rpc/internal/system/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewEntClient(confData, logger)
	dataData, cleanup, err := data.NewData(client, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userBiz := biz.NewUserBiz(userRepo, logger)
	authBiz := biz.NewAuthBiz(userRepo, logger)
	systemService := service.NewSystemService(userBiz, authBiz)
	enforcer := authz.NewAuthz(confData)
	grpcServer := server.NewGRPCServer(confServer, systemService, logger, enforcer)
	httpServer := server.NewHTTPServer(confServer, systemService, logger, enforcer)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
