// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: cms/v1/cms.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCmsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateCmsRequest) Reset() {
	*x = CreateCmsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_v1_cms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCmsRequest) ProtoMessage() {}

func (x *CreateCmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cms_v1_cms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCmsRequest.ProtoReflect.Descriptor instead.
func (*CreateCmsRequest) Descriptor() ([]byte, []int) {
	return file_cms_v1_cms_proto_rawDescGZIP(), []int{0}
}

type CreateCmsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateCmsReply) Reset() {
	*x = CreateCmsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_v1_cms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCmsReply) ProtoMessage() {}

func (x *CreateCmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_cms_v1_cms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCmsReply.ProtoReflect.Descriptor instead.
func (*CreateCmsReply) Descriptor() ([]byte, []int) {
	return file_cms_v1_cms_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCmsReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateCmsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCmsRequest) Reset() {
	*x = UpdateCmsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_v1_cms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCmsRequest) ProtoMessage() {}

func (x *UpdateCmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cms_v1_cms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCmsRequest.ProtoReflect.Descriptor instead.
func (*UpdateCmsRequest) Descriptor() ([]byte, []int) {
	return file_cms_v1_cms_proto_rawDescGZIP(), []int{2}
}

type UpdateCmsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCmsReply) Reset() {
	*x = UpdateCmsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_v1_cms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCmsReply) ProtoMessage() {}

func (x *UpdateCmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_cms_v1_cms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCmsReply.ProtoReflect.Descriptor instead.
func (*UpdateCmsReply) Descriptor() ([]byte, []int) {
	return file_cms_v1_cms_proto_rawDescGZIP(), []int{3}
}

type DeleteCmsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCmsRequest) Reset() {
	*x = DeleteCmsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_v1_cms_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCmsRequest) ProtoMessage() {}

func (x *DeleteCmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cms_v1_cms_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCmsRequest.ProtoReflect.Descriptor instead.
func (*DeleteCmsRequest) Descriptor() ([]byte, []int) {
	return file_cms_v1_cms_proto_rawDescGZIP(), []int{4}
}

type DeleteCmsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCmsReply) Reset() {
	*x = DeleteCmsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_v1_cms_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCmsReply) ProtoMessage() {}

func (x *DeleteCmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_cms_v1_cms_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCmsReply.ProtoReflect.Descriptor instead.
func (*DeleteCmsReply) Descriptor() ([]byte, []int) {
	return file_cms_v1_cms_proto_rawDescGZIP(), []int{5}
}

type GetCmsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCmsRequest) Reset() {
	*x = GetCmsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_v1_cms_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCmsRequest) ProtoMessage() {}

func (x *GetCmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cms_v1_cms_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCmsRequest.ProtoReflect.Descriptor instead.
func (*GetCmsRequest) Descriptor() ([]byte, []int) {
	return file_cms_v1_cms_proto_rawDescGZIP(), []int{6}
}

type GetCmsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCmsReply) Reset() {
	*x = GetCmsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_v1_cms_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCmsReply) ProtoMessage() {}

func (x *GetCmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_cms_v1_cms_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCmsReply.ProtoReflect.Descriptor instead.
func (*GetCmsReply) Descriptor() ([]byte, []int) {
	return file_cms_v1_cms_proto_rawDescGZIP(), []int{7}
}

type ListCmsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCmsRequest) Reset() {
	*x = ListCmsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_v1_cms_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCmsRequest) ProtoMessage() {}

func (x *ListCmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cms_v1_cms_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCmsRequest.ProtoReflect.Descriptor instead.
func (*ListCmsRequest) Descriptor() ([]byte, []int) {
	return file_cms_v1_cms_proto_rawDescGZIP(), []int{8}
}

type ListCmsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCmsReply) Reset() {
	*x = ListCmsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_v1_cms_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCmsReply) ProtoMessage() {}

func (x *ListCmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_cms_v1_cms_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCmsReply.ProtoReflect.Descriptor instead.
func (*ListCmsReply) Descriptor() ([]byte, []int) {
	return file_cms_v1_cms_proto_rawDescGZIP(), []int{9}
}

var File_cms_v1_cms_proto protoreflect.FileDescriptor

var file_cms_v1_cms_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6d, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x12,
	0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x24, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6d, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x6d, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x6d, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6d, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6d,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xd9, 0x02, 0x0a, 0x03, 0x43, 0x6d, 0x73, 0x12, 0x45,
	0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x73, 0x12, 0x1c, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x6d, 0x73, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x09,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6d, 0x73, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6d, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6d,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6d, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x43, 0x6d, 0x73, 0x12, 0x19, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6d,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6d, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x3f, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6d, 0x73, 0x12, 0x1a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6d,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6d, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x2f, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6d, 0x73, 0x2e, 0x76, 0x31,
	0x50, 0x01, 0x5a, 0x1f, 0x76, 0x69, 0x6e, 0x65, 0x2d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x2d, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6d, 0x73, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cms_v1_cms_proto_rawDescOnce sync.Once
	file_cms_v1_cms_proto_rawDescData = file_cms_v1_cms_proto_rawDesc
)

func file_cms_v1_cms_proto_rawDescGZIP() []byte {
	file_cms_v1_cms_proto_rawDescOnce.Do(func() {
		file_cms_v1_cms_proto_rawDescData = protoimpl.X.CompressGZIP(file_cms_v1_cms_proto_rawDescData)
	})
	return file_cms_v1_cms_proto_rawDescData
}

var file_cms_v1_cms_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cms_v1_cms_proto_goTypes = []interface{}{
	(*CreateCmsRequest)(nil), // 0: api.cms.v1.CreateCmsRequest
	(*CreateCmsReply)(nil),   // 1: api.cms.v1.CreateCmsReply
	(*UpdateCmsRequest)(nil), // 2: api.cms.v1.UpdateCmsRequest
	(*UpdateCmsReply)(nil),   // 3: api.cms.v1.UpdateCmsReply
	(*DeleteCmsRequest)(nil), // 4: api.cms.v1.DeleteCmsRequest
	(*DeleteCmsReply)(nil),   // 5: api.cms.v1.DeleteCmsReply
	(*GetCmsRequest)(nil),    // 6: api.cms.v1.GetCmsRequest
	(*GetCmsReply)(nil),      // 7: api.cms.v1.GetCmsReply
	(*ListCmsRequest)(nil),   // 8: api.cms.v1.ListCmsRequest
	(*ListCmsReply)(nil),     // 9: api.cms.v1.ListCmsReply
}
var file_cms_v1_cms_proto_depIdxs = []int32{
	0, // 0: api.cms.v1.Cms.CreateCms:input_type -> api.cms.v1.CreateCmsRequest
	2, // 1: api.cms.v1.Cms.UpdateCms:input_type -> api.cms.v1.UpdateCmsRequest
	4, // 2: api.cms.v1.Cms.DeleteCms:input_type -> api.cms.v1.DeleteCmsRequest
	6, // 3: api.cms.v1.Cms.GetCms:input_type -> api.cms.v1.GetCmsRequest
	8, // 4: api.cms.v1.Cms.ListCms:input_type -> api.cms.v1.ListCmsRequest
	1, // 5: api.cms.v1.Cms.CreateCms:output_type -> api.cms.v1.CreateCmsReply
	3, // 6: api.cms.v1.Cms.UpdateCms:output_type -> api.cms.v1.UpdateCmsReply
	5, // 7: api.cms.v1.Cms.DeleteCms:output_type -> api.cms.v1.DeleteCmsReply
	7, // 8: api.cms.v1.Cms.GetCms:output_type -> api.cms.v1.GetCmsReply
	9, // 9: api.cms.v1.Cms.ListCms:output_type -> api.cms.v1.ListCmsReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cms_v1_cms_proto_init() }
func file_cms_v1_cms_proto_init() {
	if File_cms_v1_cms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cms_v1_cms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCmsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_v1_cms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCmsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_v1_cms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCmsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_v1_cms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCmsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_v1_cms_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCmsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_v1_cms_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCmsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_v1_cms_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCmsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_v1_cms_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCmsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_v1_cms_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCmsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_v1_cms_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCmsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cms_v1_cms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cms_v1_cms_proto_goTypes,
		DependencyIndexes: file_cms_v1_cms_proto_depIdxs,
		MessageInfos:      file_cms_v1_cms_proto_msgTypes,
	}.Build()
	File_cms_v1_cms_proto = out.File
	file_cms_v1_cms_proto_rawDesc = nil
	file_cms_v1_cms_proto_goTypes = nil
	file_cms_v1_cms_proto_depIdxs = nil
}
